/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taschenrechnerkw11;
import javax.swing.JOptionPane;

/**
 *
 * @author TEAM Dentaltechnik
 */
public class Taschenrechner extends javax.swing.JFrame {
    String ausgabe = "hi";
    int stelle = 1;
    double zahl1 = 0;
    double zahl2 = 0;
    String opperator;
    boolean dezimal = false;
    int dfacktor = 10;

    /**
     * Creates new form Taschenrechner
     */
    public Taschenrechner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfausgabe = new javax.swing.JTextField();
        bz7 = new javax.swing.JButton();
        bz8 = new javax.swing.JButton();
        bz9 = new javax.swing.JButton();
        bza = new javax.swing.JButton();
        bzs = new javax.swing.JButton();
        bz4 = new javax.swing.JButton();
        bz5 = new javax.swing.JButton();
        bz6 = new javax.swing.JButton();
        bzm = new javax.swing.JButton();
        bz3 = new javax.swing.JButton();
        bz2 = new javax.swing.JButton();
        bz1 = new javax.swing.JButton();
        bzk = new javax.swing.JButton();
        bac = new javax.swing.JButton();
        bz0 = new javax.swing.JButton();
        bzd = new javax.swing.JButton();
        bzi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfausgabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfausgabeActionPerformed(evt);
            }
        });

        bz7.setText("7");
        bz7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bz7ActionPerformed(evt);
            }
        });

        bz8.setText("8");
        bz8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bz8ActionPerformed(evt);
            }
        });

        bz9.setText("9");
        bz9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bz9ActionPerformed(evt);
            }
        });

        bza.setText("+");
        bza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bzaActionPerformed(evt);
            }
        });

        bzs.setText("-");
        bzs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bzsActionPerformed(evt);
            }
        });

        bz4.setText("4");
        bz4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bz4ActionPerformed(evt);
            }
        });

        bz5.setText("5");
        bz5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bz5ActionPerformed(evt);
            }
        });

        bz6.setText("6");
        bz6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bz6ActionPerformed(evt);
            }
        });

        bzm.setText("*");
        bzm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bzmActionPerformed(evt);
            }
        });

        bz3.setText("3");
        bz3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bz3ActionPerformed(evt);
            }
        });

        bz2.setText("2");
        bz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bz2ActionPerformed(evt);
            }
        });

        bz1.setText("1");
        bz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bz1ActionPerformed(evt);
            }
        });

        bzk.setText(",");
        bzk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bzkActionPerformed(evt);
            }
        });

        bac.setBackground(new java.awt.Color(255, 153, 0));
        bac.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bac.setText("AC");
        bac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacActionPerformed(evt);
            }
        });

        bz0.setText("0");
        bz0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bz0ActionPerformed(evt);
            }
        });

        bzd.setText("/");
        bzd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bzdActionPerformed(evt);
            }
        });

        bzi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bzi.setText("=");
        bzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bzi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfausgabe)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bz7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(bz8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bz4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(bz5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bz9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bz6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bz1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bz2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bz0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bzk, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bz3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bzm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bzd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bzs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bza, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfausgabe, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bz7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bz8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bz9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bza, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bz4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bz5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bz6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bzs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bz1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bz2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bz3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bzm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bzk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bzd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bz0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bzi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfausgabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfausgabeActionPerformed
        tfausgabe.setText("Test");
    }//GEN-LAST:event_tfausgabeActionPerformed

    private void bz0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bz0ActionPerformed
        double menge = 0;
        if(stelle == 1){
            if(dezimal == true){
                zahl1 = zahl1 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl1 = (zahl1 * 10) + menge;
            }           
            tfausgabe.setText(toString(zahl1));
        }else{
            if(dezimal == true){
                zahl2 = zahl2 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl2 = (zahl2 * 10) + menge;
            }
        tfausgabe.setText(toString(zahl1) + opperator + toString(zahl2));
        }
       
    }//GEN-LAST:event_bz0ActionPerformed

    private void bz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bz1ActionPerformed
        double menge = 1;
        if(stelle == 1){
            if(dezimal == true){
                zahl1 = zahl1 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl1 = (zahl1 * 10) + menge;
            }           
            tfausgabe.setText(toString(zahl1));
        }else{
            if(dezimal == true){
                zahl2 = zahl2 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl2 = (zahl2 * 10) + menge;
            }
        tfausgabe.setText(toString(zahl1) + opperator + toString(zahl2));
        }
    }//GEN-LAST:event_bz1ActionPerformed

    private void bz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bz2ActionPerformed
        double menge = 2;
        if(stelle == 1){
            if(dezimal == true){
                zahl1 = zahl1 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl1 = (zahl1 * 10) + menge;
            }           
            tfausgabe.setText(toString(zahl1));
        }else{
            if(dezimal == true){
                zahl2 = zahl2 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl2 = (zahl2 * 10) + menge;
            }
        tfausgabe.setText(toString(zahl1) + opperator + toString(zahl2));
        }
    }//GEN-LAST:event_bz2ActionPerformed

    private void bz3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bz3ActionPerformed
        double menge = 3;
        if(stelle == 1){
            if(dezimal == true){
                zahl1 = zahl1 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl1 = (zahl1 * 10) + menge;
            }           
            tfausgabe.setText(toString(zahl1));
        }else{
            if(dezimal == true){
                zahl2 = zahl2 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl2 = (zahl2 * 10) + menge;
            }
        tfausgabe.setText(toString(zahl1) + opperator + toString(zahl2));
        }
    }//GEN-LAST:event_bz3ActionPerformed

    private void bz4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bz4ActionPerformed
        double menge = 4;
        if(stelle == 1){
            if(dezimal == true){
                zahl1 = zahl1 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl1 = (zahl1 * 10) + menge;
            }           
            tfausgabe.setText(toString(zahl1));
        }else{
            if(dezimal == true){
                zahl2 = zahl2 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl2 = (zahl2 * 10) + menge;
            }
        tfausgabe.setText(toString(zahl1) + opperator + toString(zahl2));
        }
    }//GEN-LAST:event_bz4ActionPerformed

    private void bz5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bz5ActionPerformed
        double menge = 5;
        if(stelle == 1){
            if(dezimal == true){
                zahl1 = zahl1 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl1 = (zahl1 * 10) + menge;
            }           
            tfausgabe.setText(toString(zahl1));
        }else{
            if(dezimal == true){
                zahl2 = zahl2 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl2 = (zahl2 * 10) + menge;
            }
        tfausgabe.setText(toString(zahl1) + opperator + toString(zahl2));
        }
    }//GEN-LAST:event_bz5ActionPerformed

    private void bz6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bz6ActionPerformed
        double menge = 6;
        if(stelle == 1){
            if(dezimal == true){
                zahl1 = zahl1 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl1 = (zahl1 * 10) + menge;
            }           
            tfausgabe.setText(toString(zahl1));
        }else{
            if(dezimal == true){
                zahl2 = zahl2 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl2 = (zahl2 * 10) + menge;
            }
        tfausgabe.setText(toString(zahl1) + opperator + toString(zahl2));
        }
    }//GEN-LAST:event_bz6ActionPerformed

    private void bz7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bz7ActionPerformed
        double menge = 7;
        if(stelle == 1){
            if(dezimal == true){
                zahl1 = zahl1 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl1 = (zahl1 * 10) + menge;
            }           
            tfausgabe.setText(toString(zahl1));
        }else{
            if(dezimal == true){
                zahl2 = zahl2 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl2 = (zahl2 * 10) + menge;
            }
        tfausgabe.setText(toString(zahl1) + opperator + toString(zahl2));
        }
    }//GEN-LAST:event_bz7ActionPerformed

    private void bz8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bz8ActionPerformed
        double menge = 8;
        if(stelle == 1){
            if(dezimal == true){
                zahl1 = zahl1 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl1 = (zahl1 * 10) + menge;
            }           
            tfausgabe.setText(toString(zahl1));
        }else{
            if(dezimal == true){
                zahl2 = zahl2 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl2 = (zahl2 * 10) + menge;
            }
        tfausgabe.setText(toString(zahl1) + opperator + toString(zahl2));
        }
    }//GEN-LAST:event_bz8ActionPerformed

    private void bz9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bz9ActionPerformed
        double menge = 9;
        if(stelle == 1){
            if(dezimal == true){
                zahl1 = zahl1 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl1 = (zahl1 * 10) + menge;
            }           
            tfausgabe.setText(toString(zahl1));
        }else{
            if(dezimal == true){
                zahl2 = zahl2 + (menge/dfacktor);
                dfacktor = dfacktor * 10;
            }else{
                zahl2 = (zahl2 * 10) + menge;
            }
        tfausgabe.setText(toString(zahl1) + opperator + toString(zahl2));
        }
    }//GEN-LAST:event_bz9ActionPerformed

    private void bzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bzaActionPerformed
        opperator = " + ";
        tfausgabe.setText(toString(zahl1)+ opperator);
        stelle = 2;
        dfacktor = 10;
        dezimal = false;
    }//GEN-LAST:event_bzaActionPerformed

    private void bzsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bzsActionPerformed
        opperator = " - ";
        tfausgabe.setText(toString(zahl1)+ opperator);
        stelle = 2;
        dfacktor = 10;
        dezimal = false;
    }//GEN-LAST:event_bzsActionPerformed

    private void bzmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bzmActionPerformed
        opperator = " * ";
        tfausgabe.setText(toString(zahl1)+ opperator);
        stelle = 2;
        dfacktor = 10;
        dezimal = false;
    }//GEN-LAST:event_bzmActionPerformed

    private void bzdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bzdActionPerformed
        opperator = " / ";
        tfausgabe.setText(toString(zahl1)+ opperator);
        stelle = 2;
        dfacktor = 10;
        dezimal = false;
    }//GEN-LAST:event_bzdActionPerformed

    private void bzkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bzkActionPerformed
        dezimal = true; 
    }//GEN-LAST:event_bzkActionPerformed

    private void bziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bziActionPerformed
        switch(opperator){
            case" + ":
                tfausgabe.setText(toString(zahl1 + zahl2));
                break;
            case" - ":
                tfausgabe.setText(toString(zahl1 - zahl2));
                break;
            case" * ":
                tfausgabe.setText(toString(zahl1 * zahl2));
                break;
            case" / ":
                tfausgabe.setText(toString(zahl1 / zahl2));
                break;
            default:
                tfausgabe.setText(toString(zahl1));
                break;
        }
    }//GEN-LAST:event_bziActionPerformed

    private void bacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacActionPerformed

    stelle = 1;
    zahl1 = 0;
    zahl2 = 0;
    dezimal = false;
    dfacktor = 10;
    tfausgabe.setText("");
    }//GEN-LAST:event_bacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taschenrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taschenrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taschenrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taschenrechner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Taschenrechner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bac;
    private javax.swing.JButton bz0;
    private javax.swing.JButton bz1;
    private javax.swing.JButton bz2;
    private javax.swing.JButton bz3;
    private javax.swing.JButton bz4;
    private javax.swing.JButton bz5;
    private javax.swing.JButton bz6;
    private javax.swing.JButton bz7;
    private javax.swing.JButton bz8;
    private javax.swing.JButton bz9;
    private javax.swing.JButton bza;
    private javax.swing.JButton bzd;
    private javax.swing.JButton bzi;
    private javax.swing.JButton bzk;
    private javax.swing.JButton bzm;
    private javax.swing.JButton bzs;
    private javax.swing.JTextField tfausgabe;
    // End of variables declaration//GEN-END:variables


    private String toString(double zahl1) {
        String stringausgabe = zahl1 + "";
        return stringausgabe;
    }
}
